[emulator]
type = "BlueStack"
config_path = "D:\\ProgramFiles\\BlueStacks_nxt\\bluestacks.conf"
path = "C:\\Program Files\\BlueStacks_nxt\\HD-Player.exe"
args = " --instance Nougat64"

[tasks]
config_path = ".\\test.toml"